---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-volume
  labels:
    type: fast-storage
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kafka-volume
spec:
  selector:
    matchLabels:
      type: kafka-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi