---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-volume
  labels:
    type: kafka-storage
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""  # Asegúrate de no usar una StorageClass
  hostPath:
    path: /volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kafka-volume
spec:
  selector:
    matchLabels:
      type: kafka-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: ""  # Deshabilita el uso de StorageClass
