Vagrant.configure("2") do |config|
  # Configuración de las máquinas virtuales
  
  # VM 1: Master
  config.vm.define "k8-master" do |master|
    master.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04 no tiene una caja oficial aún, puedes usar focal64 para propósitos similares.
    master.vm.network "public_network", ip: "192.168.100.160", bridge: "wlo1"
    master.vm.hostname = "k8-master"
    master.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/home/vagrant/.ssh/authorized_keys"

    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"  # Memoria asignada a la VM
      vb.cpus = 2          # Número de CPUs asignados
    end
  end

  # VM 2: Worker 1
  config.vm.define "k8-worker1" do |worker1|
    worker1.vm.box = "generic/alma9"
    worker1.vm.network "public_network", ip: "192.168.100.170", bridge: "wlo1"
    worker1.vm.hostname = "k8-worker-01"
    worker1.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/home/vagrant/.ssh/authorized_keys"

    worker1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end
