---
apiVersion: v1
kind: Service
metadata:
  name: kafka-dev-svc-01
spec:
  selector:
    app: kafka-dev-controller-01
    instance: kafka-dev-controller-01
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-dev-svc-02
spec:
  selector:
    app: kafka-dev-controller-02
    instance: kafka-dev-controller-02
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-dev-svc-03
spec:
  selector:
    app: kafka-dev-broker-01
    instance: kafka-dev-broker-01
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-dev-svc-04
spec:
  selector:
    app: kafka-dev-broker-02
    instance: kafka-dev-broker-02
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: control-center-svc
spec:
  type: LoadBalancer
  selector:
    app: control-center
    instance: control-center
  ports:
  - name: web
    port: 9021
    targetPort: 9021
