---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
  labels:
    app: control-center
    instance: control-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
      instance: control-center
  template:
    metadata:
      labels:
        app: control-center
        instance: control-center
    spec:
      containers:
      - name: control-center
        image: confluentinc/cp-enterprise-control-center
        resources:
          limits:
            memory: "2048Mi"
            cpu: "600m"
        env:
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: kafka-cluster-kafka-bootstrap:9092
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "1"
        - name: CONTROL_CENTER_CONNECT_TEST_CLUSTER
          value: http://kafka-connect-cluster-connect-api:8083
        - name: CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT
          value: /connector-plugins
