---
apiVersion: v1
kind: Service
metadata:
  name: kafka-controllers-svc
  labels:
    app: kafka-controllers
spec:
  clusterIP: None
  selector:
    app: kafka-controllers
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: kafka-internal
      port: 9093
      targetPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-brokers-svc
  labels:
    app: kafka-brokers
spec:
  selector:
    app: kafka-brokers
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: kafka-internal
      port: 9093
      targetPort: 9093
---
