apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-kraft-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.5.1  # Usa una versión de Kafka que soporte KRaft
    replicas: 3     # Número de brokers
    config:
      inter.broker.protocol.version: "3.5"
      log.message.format.version: "3.5"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: false
    metadataVersion: "3.5"  # Habilita el modo KRaft
  zookeeper:
    replicas: 1  # Zookeeper "falso" con un solo nodo
    storage:
      type: ephemeral  # Sin almacenamiento persistente
  entityOperator:
    topicOperator: {}
    userOperator: {}
