all:
  children:
    k8-masters:
      hosts:
        k8-master-01:
          ansible_host: 4.246.172.112
    k8-workers:
      hosts:
        k8-worker-01:
          ansible_host: 172.173.172.171
        k8-worker-02:
          ansible_host: 172.173.141.238
    k8-cluster:
      children:
        k8-masters:
        k8-workers: