---
- name: Crear cluster de kubernetes
  hosts: k8-cluster
  become: yes
  tasks:

    - name: Copiar url del repositorio a /etc/apt/sources.list.d
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"

    - name: Descargar la llave GPG de docker en formato ascii
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/containerd.gpg
        
    - name: Convertir la llave GPG de docker en binario y copiarla en /etc/apt/trusted.gpg.d
      ansible.builtin.command:
        cmd: gpg --dearmor -o /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg /tmp/containerd.gpg
        creates: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg
      register: gpg_log

    - name: Mostrar resultado de gpg
      ansible.builtin.debug:
        var: gpg_log

    - name: Copiar url del repositorio de docker a /etc/apt/sources.list.d
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"

    - name: Actualizar paquetes
      apt:
        update_cache: true
        allow_unauthenticated: yes
        upgrade: full

    # - name: Unconditionally reboot the machine with all defaults
    #   ansible.builtin.reboot:

    - name: Instalar herramientas necesarias
      apt:
        update_cache: true
        allow_unauthenticated: yes
        name:
          - curl
          - apt-transport-https
          - gnupg2
          - software-properties-common
          - ca-certificates
          - wget

    - name: Instalar herramientas de kubernetes
      apt:
        update_cache: true
        name:
          - kubelet
          - kubeadm
          - kubectl

    - name: No permitir actualizaciones de kubelet
      ansible.builtin.dpkg_selections:
        name: kubelet
        selection: hold
    
    - name: No permitir actualizaciones de kubeadm
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: hold

    - name: No permitir actualizaciones de kubectl
      ansible.builtin.dpkg_selections:
        name: kubectl
        selection: hold

    - name: Desactivar la memoria swap
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^([^#].*swap.*)'
        line: '#\1'
        backrefs: yes
    
    - name: Ejecutar comando mount
      ansible.builtin.command:
        cmd: mount -a
      register: register_mount

    - name: Mostrar el resultado de mount
      ansible.builtin.debug:
        var: register_mount.stdout
    
    - name: Add the overlay module
      community.general.modprobe:
        name: overlay
        state: present
    
    - name: Add the br_netfilter module
      community.general.modprobe:
        name: br_netfilter
        state: present

    - name: Crear o sobrescribir /etc/sysctl.d/kubernetes.conf
      ansible.builtin.copy:
        dest: /etc/sysctl.d/kubernetes.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
        owner: root
        group: root
        mode: '0644'

    - name: Ejecutar el comando sysctl
      ansible.builtin.command:
        cmd: sysctl --system
      register: sys_log

    - name: Ejecutar log de sysctl
      ansible.builtin.debug:
        var: sys_log

    - name: Crear archivo para persistir los modulos
      ansible.builtin.copy:
        dest: /etc/modules-load.d/containerd.conf
        content: |
          overlay
          br_netfilter

    - name: Instalar herramientas de kubernetes
      apt:
        update_cache: true
        name: containerd.io