---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsontest-dev-api-01
  labels:
    app: jsontest-dev-api-01
    instance: jsontest-dev-api-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsontest-dev-api-01
      instance: jsontest-dev-api-01
  template:
    metadata:
      labels:
        app: jsontest-dev-api-01
        instance: jsontest-dev-api-01
    spec:
      containers:
      - name: jsontest-dev-api-01
        image: scarmona04/json-rest:dev
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: jsontestapi-dev-svc-01
spec:
  selector:
    app: jsontest-dev-api-01
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: push-syslog-json
#   labels:
#     app: push-syslog-json
#     instance: push-syslog-json
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: push-syslog-json
#       instance: push-syslog-json
#   template:
#     metadata:
#       labels:
#         app: push-syslog-json
#         instance: push-syslog-json
#     spec:
#       containers:
#       - name: push-syslog-json
#         image: push-json-rsyslog:dev
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 8000
#         resources:
#           limits:
#             memory: "1024Mi"
#             cpu: "500m"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: push-rest-service
# spec:
#   selector:
#     app: push-syslog-json
#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000
