---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-brokers
  labels:
    app: kafka-brokers
    instance: kafka-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-brokers
      instance: kafka-b
  template:
    metadata:
      labels:
        app: kafka-brokers
        instance: kafka-b
    spec:
      containers:
      - name: broker-kafka
        image: confluentinc/cp-kafka:7.5.0
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: KAFKA_PROCESS_ROLES
          value: controller
        - name: KAFKA_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: BROKER_PLAINTEXT
        - name: KAFKA_LISTENERS
          value: CONTROLLER://:9093,BROKER_PLAINTEXT://:29092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: BROKER_PLAINTEXT://kafka-1:29092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,BROKER_PLAINTEXT:PLAINTEXT
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: 1@kafka-1:9093
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: CLUSTER_ID
          value: MkU3OEVBNTcwNTJENDM2Qk
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
spec:
  selector:
    app: kafka
    instance: kafka-1
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
