---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-controller-1
  labels:
    app: kafka-controller-1
    instance: kafka-controller-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-controller-1
      instance: kafka-controller-1
  template:
    metadata:
      labels:
        app: kafka-controller-1
        instance: kafka-controller-1
    spec:
      containers:
      - name: controller-kafka-1
        image: confluentinc/cp-kafka:7.5.0
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: KAFKA_PROCESS_ROLES
          value: controller
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: BROKER_PLAINTEXT
        - name: KAFKA_LISTENERS
          value: CONTROLLER://:9093
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,BROKER_PLAINTEXT:PLAINTEXT
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: 1@kafka-1:9093,2@kafka-2:9093
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: CLUSTER_ID
          value: MkU3OEVBNTcwNTJENDM2Qk
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
spec:
  selector:
    app: kafka-controller-1
    instance: kafka-controller-1
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-controller-2
  labels:
    app: kafka-controller-2
    instance: kafka-controller-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-controller-2
      instance: kafka-controller-2
  template:
    metadata:
      labels:
        app: kafka-controller-2
        instance: kafka-controller-2
    spec:
      containers:
      - name: controller-kafka-2
        image: confluentinc/cp-kafka:7.5.0
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: KAFKA_PROCESS_ROLES
          value: controller
        - name: KAFKA_NODE_ID
          value: "2"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: BROKER_PLAINTEXT
        - name: KAFKA_LISTENERS
          value: CONTROLLER://:9093
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,BROKER_PLAINTEXT:PLAINTEXT
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: 1@kafka-1:9093,2@kafka-2:9093
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: CLUSTER_ID
          value: MkU3OEVBNTcwNTJENDM2Qk
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
spec:
  selector:
    app: kafka-controller-2
    instance: kafka-controller-2
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-brokers-1
  labels:
    app: kafka-brokers-1
    instance: kafka-brokers-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-brokers-1
      instance: kafka-brokers-1
  template:
    metadata:
      labels:
        app: kafka-brokers-1
        instance: kafka-brokers-1
    spec:
      containers:
      - name: broker-kafka-1
        image: confluentinc/cp-kafka:7.5.0
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: KAFKA_PROCESS_ROLES
          value: broker
        - name: KAFKA_NODE_ID
          value: "3"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-3:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: 1@kafka-1:9093,2@kafka-2:9093
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: CLUSTER_ID
          value: MkU3OEVBNTcwNTJENDM2Qk
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3
spec:
  selector:
    app: kafka-brokers-1
    instance: kafka-brokers-1
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
